"""add_asset_sort_order_and_pinned

Revision ID: 088b3b050123
Revises: 5a05699f7a81
Create Date: 2026-04-11 14:08:15.663090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088b3b050123'
down_revision: Union[str, None] = '5a05699f7a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 先添加为 nullable，填充默认值后再改为 NOT NULL
    op.add_column('assets', sa.Column('sort_order', sa.Integer(), nullable=True, comment='自定义排序序号，越小越靠前'))
    op.add_column('assets', sa.Column('pinned', sa.Boolean(), nullable=True, comment='是否置顶'))
    # 给已有行填默认值
    op.execute("UPDATE assets SET sort_order = 0 WHERE sort_order IS NULL")
    op.execute("UPDATE assets SET pinned = false WHERE pinned IS NULL")
    # 改为 NOT NULL
    op.alter_column('assets', 'sort_order', nullable=False)
    op.alter_column('assets', 'pinned', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'pinned')
    op.drop_column('assets', 'sort_order')
    # ### end Alembic commands ###
