"""add_planned_includes_invested_to_asset

Revision ID: 1e1dfac446ad
Revises: a62a2297180d
Create Date: 2026-04-12 00:19:01.514139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1dfac446ad'
down_revision: Union[str, None] = 'a62a2297180d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 三步法：nullable添加 → 填充默认值 → 设为NOT NULL
    op.add_column('assets', sa.Column('planned_includes_invested', sa.Boolean(), nullable=True, comment='预计投入是否包含已投入金额'))
    op.execute("UPDATE assets SET planned_includes_invested = true")
    op.alter_column('assets', 'planned_includes_invested', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'planned_includes_invested')
    # ### end Alembic commands ###
