"""add_tx_batch_tracking

Revision ID: 2f638bc4b0ed
Revises: 3379981b1585
Create Date: 2026-04-10 10:51:43.033718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f638bc4b0ed'
down_revision: Union[str, None] = '3379981b1585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. 先创建 enum 类型
    txstatus = sa.Enum('HOLDING', 'PARTIAL_SOLD', 'CLEARED', name='txstatus')
    txstatus.create(op.get_bind(), checkfirst=True)

    # 2. 加列允许 null
    op.add_column('transactions', sa.Column('sold_quantity', sa.Numeric(precision=18, scale=4), nullable=True, comment='已卖出数量（仅买入记录）'))
    op.add_column('transactions', sa.Column('status', txstatus, nullable=True, comment='持仓状态（仅买入记录）'))
    op.add_column('transactions', sa.Column('source_tx_id', sa.Integer(), nullable=True, comment='来源买入交易ID（仅卖出记录）'))
    op.create_foreign_key(None, 'transactions', 'transactions', ['source_tx_id'], ['id'])

    # 3. 为已有数据设默认值
    op.execute("UPDATE transactions SET sold_quantity = 0 WHERE sold_quantity IS NULL")
    op.execute("UPDATE transactions SET status = 'HOLDING' WHERE status IS NULL")

    # 4. 改为 NOT NULL
    op.alter_column('transactions', 'sold_quantity', nullable=False, server_default='0')
    op.alter_column('transactions', 'status', nullable=False, server_default=sa.text("'HOLDING'"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'source_tx_id')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'sold_quantity')
    # ### end Alembic commands ###
