"""add_user_and_user_id

Revision ID: 3379981b1585
Revises: 6d9e57911c8d
Create Date: 2026-04-09 19:06:39.786431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3379981b1585'
down_revision: Union[str, None] = '6d9e57911c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('assets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'users', ['user_id'], ['id'])
    op.add_column('harbor', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_harbor_user_id'), 'harbor', ['user_id'], unique=False)
    op.create_foreign_key(None, 'harbor', 'users', ['user_id'], ['id'])
    op.add_column('harbor_goals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_harbor_goals_user_id'), 'harbor_goals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'harbor_goals', 'users', ['user_id'], ['id'])
    op.add_column('liabilities', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_liabilities_user_id'), 'liabilities', ['user_id'], unique=False)
    op.create_foreign_key(None, 'liabilities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'liabilities', type_='foreignkey')
    op.drop_index(op.f('ix_liabilities_user_id'), table_name='liabilities')
    op.drop_column('liabilities', 'user_id')
    op.drop_constraint(None, 'harbor_goals', type_='foreignkey')
    op.drop_index(op.f('ix_harbor_goals_user_id'), table_name='harbor_goals')
    op.drop_column('harbor_goals', 'user_id')
    op.drop_constraint(None, 'harbor', type_='foreignkey')
    op.drop_index(op.f('ix_harbor_user_id'), table_name='harbor')
    op.drop_column('harbor', 'user_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_column('assets', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
