"""add_total_recovered_and_default_currency

Revision ID: 3d37a48d64a0
Revises: f7a7d0b2028e
Create Date: 2026-04-15 16:58:16.409397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d37a48d64a0'
down_revision: Union[str, None] = 'f7a7d0b2028e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('total_recovered', sa.Numeric(precision=18, scale=4), nullable=False, server_default='0', comment='累计卖出回收本金（卖出总额-手续费-利润）'))
    op.add_column('users', sa.Column('default_currency', sa.String(length=8), nullable=False, server_default='CNY', comment='默认显示货币: CNY/USD/HKD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_currency')
    op.drop_column('assets', 'total_recovered')
    # ### end Alembic commands ###
