"""add_user_email_theme_avatar

Revision ID: 5a05699f7a81
Revises: f2bc2a8bba2a
Create Date: 2026-04-10 23:26:23.845983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a05699f7a81'
down_revision: Union[str, None] = 'f2bc2a8bba2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('theme', sa.String(length=32), nullable=False, server_default='emerald'))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
