"""init_all_tables

Revision ID: 6d9e57911c8d
Revises: 
Create Date: 2026-04-09 17:18:41.399535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9e57911c8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='标的代码 如 NVDA / BTC'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='显示名称'),
    sa.Column('zone', sa.Enum('ACTIVE', 'BASE', name='assetzone'), nullable=False),
    sa.Column('category', sa.Enum('STOCK', 'ETF', 'CRYPTO', 'DEPOSIT', 'BOND_FUND', 'PENSION', 'GOLD', 'COLLECTIBLE', 'REAL_ESTATE', name='assetcategory'), nullable=False),
    sa.Column('broker_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='券商真实成本价'),
    sa.Column('mental_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='心理成本价（博弈账本）'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='持仓数量'),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=False, comment='当前市价'),
    sa.Column('total_invested', sa.Numeric(precision=18, scale=4), nullable=False, comment='累计投入本金'),
    sa.Column('total_cashed', sa.Numeric(precision=18, scale=4), nullable=False, comment='累计已套现利润'),
    sa.Column('is_zero_cost', sa.Boolean(), nullable=False, comment='是否已达成零成本'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_index(op.f('ix_assets_zone'), 'assets', ['zone'], unique=False)
    op.create_table('harbor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False, comment='当前余额'),
    sa.Column('total_in', sa.Numeric(precision=18, scale=4), nullable=False, comment='累计转入'),
    sa.Column('total_out', sa.Numeric(precision=18, scale=4), nullable=False, comment='累计支出'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harbor_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='目标名称'),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='目标金额'),
    sa.Column('saved_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='已存金额'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='负债名称'),
    sa.Column('liability_type', sa.Enum('MORTGAGE', 'CAR_LOAN', 'CREDIT_CARD', name='liabilitytype'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='总负债'),
    sa.Column('remaining_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='剩余待还'),
    sa.Column('monthly_payment', sa.Numeric(precision=18, scale=4), nullable=False, comment='月供'),
    sa.Column('profit_repaid', sa.Numeric(precision=18, scale=4), nullable=False, comment='投资利润累计还贷金额'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.Enum('BUY', 'SELL', 'T_TRADE', name='transactiontype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False, comment='成交价'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='成交数量'),
    sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=False, comment='手续费/印花税'),
    sa.Column('realized_profit', sa.Numeric(precision=18, scale=4), nullable=False, comment='实现利润'),
    sa.Column('note', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_asset_id'), 'transactions', ['asset_id'], unique=False)
    op.create_table('profit_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False, comment='来源卖出交易'),
    sa.Column('allocation_type', sa.Enum('SELF_OFFSET', 'CROSS_SAVE', 'TO_HARBOR', name='allocationtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='分配金额'),
    sa.Column('target_asset_id', sa.Integer(), nullable=True, comment='目标资产（跨标的时使用）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_allocations_transaction_id'), 'profit_allocations', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profit_allocations_transaction_id'), table_name='profit_allocations')
    op.drop_table('profit_allocations')
    op.drop_index(op.f('ix_transactions_asset_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('liabilities')
    op.drop_table('harbor_goals')
    op.drop_table('harbor')
    op.drop_index(op.f('ix_assets_zone'), table_name='assets')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
