"""add cash accounts and asset investment planning

Revision ID: a62a2297180d
Revises: e8b4e2999597
Create Date: 2026-04-11 17:56:34.820489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62a2297180d'
down_revision: Union[str, None] = 'e8b4e2999597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_accounts_id'), 'cash_accounts', ['id'], unique=False)
    op.create_table('funding_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='资金池名称'),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='总资金'),
    sa.Column('available_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='可用资金'),
    sa.Column('reserved_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='预留资金'),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='已投资金额'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='货币代码'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_pools_user_id'), 'funding_pools', ['user_id'], unique=False)
    op.create_table('asset_fundings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='计划投入金额'),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='已分配金额'),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='已投入金额'),
    sa.Column('returned_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='已回收金额'),
    sa.Column('profit_amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='已实现利润'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='fundingstatus'), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=True, comment='资金策略'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['funding_pools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_fundings_asset_id'), 'asset_fundings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_fundings_pool_id'), 'asset_fundings', ['pool_id'], unique=False)
    op.create_index(op.f('ix_asset_fundings_user_id'), 'asset_fundings', ['user_id'], unique=False)
    op.create_table('funding_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funding_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.Enum('ALLOCATE', 'INVEST', 'RETURN', 'PROFIT', 'TRANSFER', name='fundingtransactiontype'), nullable=False, comment='交易类型'),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='交易金额'),
    sa.Column('pool_balance_after', sa.Numeric(precision=18, scale=4), nullable=False, comment='资金池交易后余额'),
    sa.Column('funding_balance_after', sa.Numeric(precision=18, scale=4), nullable=False, comment='分配交易后余额'),
    sa.Column('related_tx_id', sa.Integer(), nullable=True, comment='关联交易ID'),
    sa.Column('related_asset_id', sa.Integer(), nullable=True, comment='关联资产ID'),
    sa.Column('note', sa.String(length=256), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funding_id'], ['asset_fundings.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['funding_pools.id'], ),
    sa.ForeignKeyConstraint(['related_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['related_tx_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_transactions_funding_id'), 'funding_transactions', ['funding_id'], unique=False)
    op.create_index(op.f('ix_funding_transactions_pool_id'), 'funding_transactions', ['pool_id'], unique=False)
    op.create_index(op.f('ix_funding_transactions_user_id'), 'funding_transactions', ['user_id'], unique=False)
    op.add_column('assets', sa.Column('planned_investment', sa.Numeric(precision=18, scale=4), nullable=True, comment='预计投入金额'))
    op.add_column('assets', sa.Column('actual_investment', sa.Numeric(precision=18, scale=4), nullable=True, comment='实际已投入金额'))
    op.add_column('assets', sa.Column('is_cash', sa.Boolean(), nullable=True, comment='是否为现金资产'))
    # 设置默认值
    op.execute("UPDATE assets SET planned_investment = 0, actual_investment = 0, is_cash = false")
    # 修改列为NOT NULL
    op.alter_column('assets', 'planned_investment', nullable=False)
    op.alter_column('assets', 'actual_investment', nullable=False)
    op.alter_column('assets', 'is_cash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'is_cash')
    op.drop_column('assets', 'actual_investment')
    op.drop_column('assets', 'planned_investment')
    op.drop_index(op.f('ix_funding_transactions_user_id'), table_name='funding_transactions')
    op.drop_index(op.f('ix_funding_transactions_pool_id'), table_name='funding_transactions')
    op.drop_index(op.f('ix_funding_transactions_funding_id'), table_name='funding_transactions')
    op.drop_table('funding_transactions')
    op.drop_index(op.f('ix_asset_fundings_user_id'), table_name='asset_fundings')
    op.drop_index(op.f('ix_asset_fundings_pool_id'), table_name='asset_fundings')
    op.drop_index(op.f('ix_asset_fundings_asset_id'), table_name='asset_fundings')
    op.drop_table('asset_fundings')
    op.drop_index(op.f('ix_funding_pools_user_id'), table_name='funding_pools')
    op.drop_table('funding_pools')
    op.drop_index(op.f('ix_cash_accounts_id'), table_name='cash_accounts')
    op.drop_table('cash_accounts')
    # ### end Alembic commands ###
