"""add_sell_batch_items

Revision ID: ccc3f8f02c5b
Revises: 2f638bc4b0ed
Create Date: 2026-04-10 11:50:51.718716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc3f8f02c5b'
down_revision: Union[str, None] = '2f638bc4b0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sell_batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sell_tx_id', sa.Integer(), nullable=False),
    sa.Column('buy_tx_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['buy_tx_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['sell_tx_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sell_batch_items_buy_tx_id'), 'sell_batch_items', ['buy_tx_id'], unique=False)
    op.create_index(op.f('ix_sell_batch_items_sell_tx_id'), 'sell_batch_items', ['sell_tx_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sell_batch_items_sell_tx_id'), table_name='sell_batch_items')
    op.drop_index(op.f('ix_sell_batch_items_buy_tx_id'), table_name='sell_batch_items')
    op.drop_table('sell_batch_items')
    # ### end Alembic commands ###
