"""add price_session to assets

Revision ID: ccff89f26dea
Revises: ff8cdd2a65cb
Create Date: 2026-04-18 17:14:12.194013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccff89f26dea'
down_revision: Union[str, None] = 'ff8cdd2a65cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('price_session', sa.String(length=16), nullable=False, server_default='', comment='价格时段: pre_market/regular/post_market/closed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'price_session')
    # ### end Alembic commands ###
