"""add_archived_fields

Revision ID: e4ed1afee03a
Revises: ffb3b1503cb8
Create Date: 2026-04-12 21:07:28.646517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ed1afee03a'
down_revision: Union[str, None] = 'ffb3b1503cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 三步法：先 nullable，填充默认值，再 NOT NULL
    op.add_column('assets', sa.Column('archived', sa.Boolean(), nullable=True, comment='是否已归档（清仓/不再关注）'))
    op.add_column('assets', sa.Column('archived_note', sa.String(length=256), nullable=True, comment='归档备注'))
    op.execute("UPDATE assets SET archived = false WHERE archived IS NULL")
    op.alter_column('assets', 'archived', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'archived_note')
    op.drop_column('assets', 'archived')
    # ### end Alembic commands ###
