"""add_salary_income_and_extend_liability

Revision ID: e8b4e2999597
Revises: 088b3b050123
Create Date: 2026-04-11 15:07:41.400785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b4e2999597'
down_revision: Union[str, None] = '088b3b050123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 扩展 LiabilityType 枚举
    op.execute("ALTER TYPE liabilitytype ADD VALUE IF NOT EXISTS 'STUDENT_LOAN'")
    op.execute("ALTER TYPE liabilitytype ADD VALUE IF NOT EXISTS 'PERSONAL_LOAN'")
    op.execute("ALTER TYPE liabilitytype ADD VALUE IF NOT EXISTS 'OTHER'")

    op.create_table('salary_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=18, scale=2), nullable=False, comment='税前月薪'),
    sa.Column('pay_day', sa.Integer(), nullable=False, comment='发薪日(1-31)'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='货币 CNY/USD'),
    sa.Column('country', sa.Enum('CN', 'US', 'CUSTOM', name='taxcountry'), nullable=False, comment='税制国家'),
    sa.Column('pension_rate', sa.Numeric(precision=6, scale=4), nullable=False, comment='养老保险 8%'),
    sa.Column('medical_rate', sa.Numeric(precision=6, scale=4), nullable=False, comment='医疗保险 2%'),
    sa.Column('unemployment_rate', sa.Numeric(precision=6, scale=4), nullable=False, comment='失业保险 0.5%'),
    sa.Column('housing_fund_rate', sa.Numeric(precision=6, scale=4), nullable=False, comment='公积金 7%'),
    sa.Column('special_deduction', sa.Numeric(precision=18, scale=2), nullable=False, comment='专项附加扣除/月'),
    sa.Column('custom_tax_rate', sa.Numeric(precision=6, scale=4), nullable=True, comment='自定义固定税率'),
    sa.Column('custom_deductions', sa.Numeric(precision=18, scale=2), nullable=True, comment='自定义免征额/月'),
    sa.Column('custom_brackets', sa.Text(), nullable=True, comment='自定义累进税率表 JSON'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_configs_user_id'), 'salary_configs', ['user_id'], unique=False)
    op.create_table('income_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary_config_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('SALARY', 'BONUS', 'FREELANCE', 'INVESTMENT', 'OTHER', name='incomesource'), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='税前金额'),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='税后到手'),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False, comment='个税'),
    sa.Column('social_insurance', sa.Numeric(precision=18, scale=2), nullable=False, comment='社保(养老+医疗+失业)'),
    sa.Column('housing_fund', sa.Numeric(precision=18, scale=2), nullable=False, comment='公积金'),
    sa.Column('month', sa.String(length=7), nullable=False, comment='所属月份 YYYY-MM'),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False, comment='是否自动生成'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salary_config_id'], ['salary_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_records_month'), 'income_records', ['month'], unique=False)
    op.create_index(op.f('ix_income_records_user_id'), 'income_records', ['user_id'], unique=False)
    op.add_column('liabilities', sa.Column('interest_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='年利率 %'))
    op.add_column('liabilities', sa.Column('start_date', sa.Date(), nullable=True, comment='起始日期'))
    op.add_column('liabilities', sa.Column('end_date', sa.Date(), nullable=True, comment='到期日期'))
    op.execute("UPDATE liabilities SET interest_rate = 0 WHERE interest_rate IS NULL")
    op.alter_column('liabilities', 'interest_rate', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liabilities', 'end_date')
    op.drop_column('liabilities', 'start_date')
    op.drop_column('liabilities', 'interest_rate')
    op.drop_index(op.f('ix_income_records_user_id'), table_name='income_records')
    op.drop_index(op.f('ix_income_records_month'), table_name='income_records')
    op.drop_table('income_records')
    op.drop_index(op.f('ix_salary_configs_user_id'), table_name='salary_configs')
    op.drop_table('salary_configs')
    # ### end Alembic commands ###
