"""add_shares_table

Revision ID: ec24824d7da6
Revises: e4ed1afee03a
Create Date: 2026-04-14 15:51:17.885904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec24824d7da6'
down_revision: Union[str, None] = 'e4ed1afee03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_code', sa.String(length=32), nullable=False, comment='分享短码'),
    sa.Column('share_type', sa.String(length=32), nullable=False, comment='分享类型: card=投资名片, snapshot=持仓快照'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='标题'),
    sa.Column('snapshot_data', sa.Text(), nullable=False, comment='JSON 快照数据'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='查看次数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间（null=永不过期）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_share_code'), 'shares', ['share_code'], unique=True)
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_share_code'), table_name='shares')
    op.drop_table('shares')
    # ### end Alembic commands ###
