"""add_notifications_table

Revision ID: f235284f38fa
Revises: 08bacd9e871c
Create Date: 2026-04-15 22:32:52.525488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f235284f38fa'
down_revision: Union[str, None] = '08bacd9e871c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='接收通知的用户'),
    sa.Column('from_user_id', sa.Integer(), nullable=False, comment='触发通知的用户'),
    sa.Column('ntype', sa.String(length=32), nullable=False, comment='通知类型: comment / reply / like / follow'),
    sa.Column('share_id', sa.Integer(), nullable=True, comment='关联的分享'),
    sa.Column('comment_id', sa.Integer(), nullable=True, comment='关联的评论'),
    sa.Column('content', sa.String(length=256), nullable=False, comment='通知摘要'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_from_user_id'), 'notifications', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_from_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
