"""add_trade_plans_table

Revision ID: f2bc2a8bba2a
Revises: a1b2c3d4e5f6
Create Date: 2026-04-10 20:00:45.523046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bc2a8bba2a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='planstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('target_position', sa.Numeric(precision=18, scale=4), nullable=False, comment='目标仓位(股数)'),
    sa.Column('max_position', sa.Numeric(precision=18, scale=4), nullable=False, comment='最大仓位上限'),
    sa.Column('build_low', sa.Numeric(precision=18, scale=4), nullable=True, comment='建仓区间下限'),
    sa.Column('build_high', sa.Numeric(precision=18, scale=4), nullable=True, comment='建仓区间上限'),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=4), nullable=True, comment='止损价'),
    sa.Column('take_profit_1', sa.Numeric(precision=18, scale=4), nullable=True, comment='第一止盈位'),
    sa.Column('take_profit_2', sa.Numeric(precision=18, scale=4), nullable=True, comment='第二止盈位'),
    sa.Column('take_profit_3', sa.Numeric(precision=18, scale=4), nullable=True, comment='第三止盈位'),
    sa.Column('support_1', sa.Numeric(precision=18, scale=4), nullable=True, comment='支撑位1'),
    sa.Column('support_2', sa.Numeric(precision=18, scale=4), nullable=True, comment='支撑位2'),
    sa.Column('resistance_1', sa.Numeric(precision=18, scale=4), nullable=True, comment='压力位1'),
    sa.Column('resistance_2', sa.Numeric(precision=18, scale=4), nullable=True, comment='压力位2'),
    sa.Column('buy_strategy', sa.Text(), nullable=True, comment='买入策略'),
    sa.Column('sell_strategy', sa.Text(), nullable=True, comment='卖出策略'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注/交易纪律'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_plans_asset_id'), 'trade_plans', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_plans_asset_id'), table_name='trade_plans')
    op.drop_table('trade_plans')
    # ### end Alembic commands ###
