"""add_ibkr_lots_table

Revision ID: ff8cdd2a65cb
Revises: f235284f38fa
Create Date: 2026-04-18 16:26:06.077941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8cdd2a65cb'
down_revision: Union[str, None] = 'f235284f38fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibkr_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='股票代码'),
    sa.Column('open_datetime', sa.String(length=32), nullable=False, comment='买入时间 如 2026-02-09, 13:21:14'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='持有数量'),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=4), nullable=False, comment='每股成本价'),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=4), nullable=False, comment='成本基础(含佣金)'),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False, comment='收盘价'),
    sa.Column('market_value', sa.Numeric(precision=18, scale=4), nullable=False, comment='市值'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=False, comment='未实现损益'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ibkr_lots_asset_id'), 'ibkr_lots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ibkr_lots_symbol'), 'ibkr_lots', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ibkr_lots_symbol'), table_name='ibkr_lots')
    op.drop_index(op.f('ix_ibkr_lots_asset_id'), table_name='ibkr_lots')
    op.drop_table('ibkr_lots')
    # ### end Alembic commands ###
