"""add_market_to_asset

Revision ID: ffb3b1503cb8
Revises: 1e1dfac446ad
Create Date: 2026-04-12 01:18:43.596734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb3b1503cb8'
down_revision: Union[str, None] = '1e1dfac446ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. nullable 添加
    op.add_column('assets', sa.Column('market', sa.String(length=16), nullable=True, comment='市场: us/cn/hk/crypto/other'))

    # 2. 已有数据自动识别填充
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, symbol, category FROM assets")).fetchall()

    import re
    for row in rows:
        aid, sym, cat = row[0], row[1].strip().upper(), row[2].lower() if row[2] else ""
        if cat == "crypto":
            market = "crypto"
        elif cat not in ("stock", "etf"):
            market = "other"
        elif re.match(r"^\d{6}$", sym) or re.match(r"^\d{6}\.(SH|SZ|BJ)$", sym):
            market = "cn"
        elif re.match(r"^\d{4,5}$", sym) or re.match(r"^\d{4,5}\.HK$", sym):
            market = "hk"
        elif re.match(r"^[A-Z]{1,5}(\.[A-Z])?$", sym):
            market = "us"
        else:
            market = "other"
        conn.execute(sa.text("UPDATE assets SET market = :m WHERE id = :id"), {"m": market, "id": aid})

    # 3. 填充剩余 NULL 为 other，然后设 NOT NULL
    conn.execute(sa.text("UPDATE assets SET market = 'other' WHERE market IS NULL"))
    op.alter_column('assets', 'market', nullable=False)
    op.create_index(op.f('ix_assets_market'), 'assets', ['market'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_market'), table_name='assets')
    op.drop_column('assets', 'market')
    # ### end Alembic commands ###
