"""Provider-independent quantitative strategy engines."""

from app.core.quant_strategies.chang_five_day import (
    DEFAULT_PARAMETERS,
    DEFAULT_MARKET_DATA_SOURCE,
    STRATEGY_KEY,
    STRATEGY_VERSION,
    ChangFiveDayMetrics,
    ChangFiveDayParameters,
    ChangFiveDayResult,
    PositionContext,
    ThreeLowQualification,
    evaluate_chang_five_day,
)
from app.core.quant_strategies.volume_ratio import (
    DEFAULT_PARAMETERS as VOLUME_RATIO_DEFAULT_PARAMETERS,
    DEFAULT_MARKET_DATA_SOURCE as VOLUME_RATIO_DEFAULT_MARKET_DATA_SOURCE,
    STRATEGY_KEY as VOLUME_RATIO_STRATEGY_KEY,
    STRATEGY_VERSION as VOLUME_RATIO_STRATEGY_VERSION,
    VolumeRatioMetrics,
    VolumeRatioParameters,
    VolumeRatioResult,
    evaluate_volume_ratio,
)
from app.core.quant_strategies.price_anchor import (
    DEFAULT_PARAMETERS as PRICE_ANCHOR_DEFAULT_PARAMETERS,
    DEFAULT_MARKET_DATA_SOURCE as PRICE_ANCHOR_DEFAULT_MARKET_DATA_SOURCE,
    STRATEGY_KEY as PRICE_ANCHOR_STRATEGY_KEY,
    STRATEGY_VERSION as PRICE_ANCHOR_STRATEGY_VERSION,
    PriceAnchorMetrics,
    PriceAnchorParameters,
    PriceAnchorResult,
    evaluate_price_anchor,
)

__all__ = [
    "DEFAULT_PARAMETERS",
    "DEFAULT_MARKET_DATA_SOURCE",
    "STRATEGY_KEY",
    "STRATEGY_VERSION",
    "ChangFiveDayMetrics",
    "ChangFiveDayParameters",
    "ChangFiveDayResult",
    "PositionContext",
    "ThreeLowQualification",
    "evaluate_chang_five_day",
    "VOLUME_RATIO_DEFAULT_PARAMETERS",
    "VOLUME_RATIO_DEFAULT_MARKET_DATA_SOURCE",
    "VOLUME_RATIO_STRATEGY_KEY",
    "VOLUME_RATIO_STRATEGY_VERSION",
    "VolumeRatioMetrics",
    "VolumeRatioParameters",
    "VolumeRatioResult",
    "evaluate_volume_ratio",
    "PRICE_ANCHOR_DEFAULT_PARAMETERS",
    "PRICE_ANCHOR_DEFAULT_MARKET_DATA_SOURCE",
    "PRICE_ANCHOR_STRATEGY_KEY",
    "PRICE_ANCHOR_STRATEGY_VERSION",
    "PriceAnchorMetrics",
    "PriceAnchorParameters",
    "PriceAnchorResult",
    "evaluate_price_anchor",
]
