"""Initial public editorial copy. Future directions are not shipped promises."""
DEFAULT_ABOUT = {
    "zh-CN": {
        "title": "让每一次投资判断，都有依据可循",
        "intro": "SeekCost 是我为认真对待自己投资判断的人开发的个人决策工作台。它不是另一个让人不停刷行情的屏幕，而是帮助我少看无关信息、少忘重要判断，在值得关注的变化发生时重新思考。",
        "mission": "我为什么开发 SeekCost\n\n关注的公司越来越多，资料散落在不同地方。看过一篇研究、记住一个价格，并不意味着下一次面对市场时，还记得当初为什么关注它。\n\n我希望有一个地方，能持续记住四件事：我为什么关注这家公司；我在等什么条件；什么情况说明我错了；后来这个判断怎么样。\n\n所以我开发 SeekCost，把股票池、研究、价格观察、提醒和复盘连接起来。它不替我做决定，而是帮助我在决定之前找到依据，在决定之后留下可以回看的记录。",
        "values": "把注意力留给真正重要的变化\n从众多标的中筛选值得复核的信号，不把每一次波动都变成行动理由。\n\n把关注变成有条件的等待\n通过研究阶段、价格锚点和自定义提醒，区分“我喜欢这家公司”和“我已经准备好行动”。\n\n保存自己的判断，而不只是收藏资料\n记录核心逻辑、支持证据、失效条件和下一次检查事项，让研究可以被验证，也可以被推翻。\n\n让经验有机会积累\n连接投资记录与复盘，逐步看清判断、价格、仓位和执行各自带来的影响。当前这些环节仍在持续完善。",
        "roadmap": "以下是计划优化的方向，不代表已经上线，也不是交付时间承诺。\n\n优先建立信任\n统一行情时间、策略计算时间和信号有效状态；清楚区分未检测、数据不足与没有触发，避免把旧结论当成当前机会。\n\n让工作台回答“今天先看什么”\n优先呈现新变化、与持仓有关的风险和待验证事项，而不是堆满所有数据。明确区分系统信号、我的判断与执行计划。\n\n打通提醒到复盘的路径\n从触发依据进入个股判断，记录继续观察、安排研究或作出决定，再回看当时的依据；逐步完善提醒合并、免打扰与检测健康状态。\n\n降低研究与操作负担\n先写清为什么关注、等什么条件、什么情况说明我错了，再按需深入。持续优化价格与图表交互，让电脑适合深入研究、手机适合处理变化。\n\n逐步看见整体风险与决策质量\n在可靠的持仓和历史记录基础上，完善组合集中度、计划执行与复盘反馈。不以一个看似精确的分数替代判断。",
    },
    "en": {
        "title": "Give every investment judgment a traceable basis",
        "intro": "I built SeekCost as a personal decision workspace for people who take their investment judgments seriously. It is not another screen to watch endlessly: it helps keep attention on meaningful changes and remember the reasoning behind a decision.",
        "mission": "Why I built SeekCost\n\nAs the list of companies grows, research becomes scattered and the original reasons for following a business are easily forgotten.\n\nI wanted one place to remember why I care, what I am waiting for, what would prove me wrong, and what happened afterward.\n\nSeekCost connects watchlists, research, price observations, alerts and review. It does not decide for me. It helps me find evidence before deciding and leave a record I can revisit afterward.",
        "values": "Protect attention\nSurface changes worth reviewing without treating every price move as a reason to act.\n\nMake waiting intentional\nResearch stages, price anchors and custom alerts separate interest in a business from readiness to act.\n\nPreserve judgments, not just documents\nKeep the thesis, evidence, invalidation conditions and next checks together. A useful view must be open to revision.\n\nBuild on experience\nConnect investment records and reviews to understand the roles of judgment, price, sizing and execution. These connections are still evolving.",
        "roadmap": "These are planned directions, not shipped features or delivery-date commitments.\n\nTrust first\nMake quote time, evaluation time and signal validity explicit. Distinguish unchecked, insufficient data and no trigger; do not present stale conclusions as current opportunities.\n\nA workbench for today's attention\nPrioritize new changes, portfolio-relevant risks and pending checks. Clearly distinguish system signals, personal judgments and execution plans.\n\nConnect alerts to review\nMove from trigger evidence to a stock's thesis, record a response and revisit the decision. Improve grouping, quiet hours and monitoring health.\n\nReduce research and interaction overhead\nStart with why I care, what I am waiting for and what would prove me wrong. Improve price and chart interactions, with deeper research on desktop and quick attention management on mobile.\n\nUnderstand portfolio risk and decision quality\nBuild concentration checks, plan tracking and review feedback on reliable holdings and historical evidence, rather than a deceptively precise score.",
    },
}
